
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Enlang {
    using System;
    using Terminal.Gui;
    
    
    public partial class Interactive : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme redOnBlack;
        
        private Terminal.Gui.TextView tx_inputbox;
        
        private Terminal.Gui.Label lb_fname;
        
        private Terminal.Gui.Label lb_filename;
        
        private Terminal.Gui.MenuBar menubox;
        
        private Terminal.Gui.MenuBarItem fileMenu;
        
        private Terminal.Gui.MenuItem openFileMenuItem;
        
        private Terminal.Gui.MenuItem saveFileMenuItem;
        
        private Terminal.Gui.MenuItem saveAsMenuItem;
        
        private Terminal.Gui.MenuBarItem aboutMenu;
        
        private Terminal.Gui.MenuItem aboutEnlangEditMenuItem;
        
        private Terminal.Gui.MenuItem menuItem;
        
        private void InitializeComponent() {
            this.menubox = new Terminal.Gui.MenuBar();
            this.lb_filename = new Terminal.Gui.Label();
            this.lb_fname = new Terminal.Gui.Label();
            this.tx_inputbox = new Terminal.Gui.TextView();
            this.redOnBlack = new Terminal.Gui.ColorScheme();
            this.redOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Black);
            this.redOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Black);
            this.redOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Red, Terminal.Gui.Color.Brown);
            this.redOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightRed, Terminal.Gui.Color.Brown);
            this.redOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.redOnBlack;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = " Enlang Editor";
            this.tx_inputbox.Width = 151;
            this.tx_inputbox.Height = 35;
            this.tx_inputbox.X = 2;
            this.tx_inputbox.Y = 2;
            this.tx_inputbox.Visible = true;
            this.tx_inputbox.ColorScheme = this.redOnBlack;
            this.tx_inputbox.AllowsTab = true;
            this.tx_inputbox.AllowsReturn = true;
            this.tx_inputbox.WordWrap = false;
            this.tx_inputbox.Data = "tx_inputbox";
            this.tx_inputbox.Text = "";
            this.tx_inputbox.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.tx_inputbox);
            this.lb_fname.Width = 5;
            this.lb_fname.Height = 1;
            this.lb_fname.X = 2;
            this.lb_fname.Y = 38;
            this.lb_fname.Visible = true;
            this.lb_fname.Data = "lb_fname";
            this.lb_fname.Text = "None";
            this.lb_fname.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lb_fname);
            this.lb_filename.Width = 4;
            this.lb_filename.Height = 1;
            this.lb_filename.X = 1;
            this.lb_filename.Y = 45;
            this.lb_filename.Visible = true;
            this.lb_filename.Data = "lb_filename";
            this.lb_filename.Text = "None";
            this.lb_filename.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lb_filename);
            this.menubox.Width = Dim.Fill(0);
            this.menubox.Height = 1;
            this.menubox.X = 0;
            this.menubox.Y = 0;
            this.menubox.Visible = true;
            this.menubox.Data = "menubox";
            this.menubox.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.fileMenu = new Terminal.Gui.MenuBarItem();
            this.fileMenu.Title = "File";
            this.openFileMenuItem = new Terminal.Gui.MenuItem();
            this.openFileMenuItem.Title = "Open File";
            this.openFileMenuItem.Data = "openFileMenuItem";
            this.saveFileMenuItem = new Terminal.Gui.MenuItem();
            this.saveFileMenuItem.Title = "Save File";
            this.saveFileMenuItem.Data = "saveFileMenuItem";
            this.saveAsMenuItem = new Terminal.Gui.MenuItem();
            this.saveAsMenuItem.Title = "Save As";
            this.saveAsMenuItem.Data = "saveAsMenuItem";
            this.fileMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.openFileMenuItem,
                    this.saveFileMenuItem,
                    this.saveAsMenuItem};
            this.aboutMenu = new Terminal.Gui.MenuBarItem();
            this.aboutMenu.Title = "About";
            this.aboutEnlangEditMenuItem = new Terminal.Gui.MenuItem();
            this.aboutEnlangEditMenuItem.Title = "About Enlang Edit";
            this.aboutEnlangEditMenuItem.Data = "aboutEnlangEditMenuItem";
            this.menuItem = new Terminal.Gui.MenuItem();
            this.menuItem.Title = "";
            this.menuItem.Data = "menuItem";
            this.aboutMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.aboutEnlangEditMenuItem,
                    this.menuItem};
            this.menubox.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileMenu,
                    this.aboutMenu};
            this.Add(this.menubox);
        }
    }
}
