
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Enlang {
    using System.Collections.Immutable;
    using System.Reflection.PortableExecutable;
    using Terminal.Gui;
    
    
    public partial class Interactive {
        SaveDialog sd;
        OpenDialog od;
        List<string> lines;
        private string filename { get; set; }
        string[] ftypes = { ".tscl",".enl",".*"};

        public Interactive() {
            InitializeComponent();
            lines = new List<string>();
            openFileMenuItem.Action += OpenFile;
            saveFileMenuItem.Action += SaveFile;
            aboutEnlangEditMenuItem.Action += DisplayAbout;
        }



        private void DisplayAbout()
        {
            string msg = @"
    Enlang is a Interpreter Programming Langauge
Made by Patrick Cortez in 2026. This Editor is made
using the framework 'Terminal.Gui'. Enlang is under 
GNU GPL v3 license, To Quit this Editor simply 
'CTRL' + 'Q'.";
            MessageBox.Query("Information",msg,"Ok");
        }

        private void OpenFile()
        {

                od = new OpenDialog();

                od.AllowedFileTypes = ftypes;
                Application.Run(od);

                if (od.FilePath != null)
                {

                    filename = od.FilePath.ToString();
                    lb_fname.Text = filename;

                    tx_inputbox.LoadFile(filename);

                }
                else
                {
                    MessageBox.Query("Error", "No File was chosen!", "Ok");
                }
        }

        private void SaveFile()
        {
            lines = new List<string>(tx_inputbox.Text.ToString().Split(new[] { "\r\n" , "\r", "\n" },StringSplitOptions.None)).ToList();

            using (StreamWriter sw = new StreamWriter(filename,false))
            {
                foreach(string line in lines)
                {
                    sw.WriteLine(line);
                }
            }
           
       }

        private void SaveAs()
        {
            sd = new SaveDialog();
            lines = new List<string>(tx_inputbox.Text.ToString().Split(new[] { "\r\n", "\r", "\n" }, StringSplitOptions.None)).ToList();

            Application.Run(sd);
            sd.AllowedFileTypes = ftypes;

            filename = sd.FilePath.ToString();

            if (!File.Exists(filename))
            {
                File.Create(filename);
            }
            else
            {
                MessageBox.Query("Warning","File already exists!","Ok");
                return;
                        
            }
            File.WriteAllLines(filename,lines);
        }


    }
}
